kotlin.code.style = official
org.gradle.jvmargs = -Xmx1G

deps.api.fabric=0.124.2+1.21.5
deps.api.architectury=16.1.4
deps.api.silk=1.10.7
deps.api.owo=0.12.21+1.21.5
deps.api.immediatelyfast=1.9.3+1.21.5-fabric
deps.api.modmenu=14.0.0-rc.2
deps.api.geckolib=5.0.2
deps.api.waveycapes=A8HBEAVx
deps.api.simplevoicechat=fabric-1.21.5-2.5.29
deps.api.xaerominimap=25.2.0_Fabric_1.21.5
deps.api.3dskinlayers=qFwcwulG
deps.api.appleskin=VfjnbBAT
deps.api.shulkerboxtooltip=5.2.5+1.21.5-fabric
deps.api.tiertagger=2.1.1+mc1.21.5
deps.api.ukulib=1.7.1+1.21.5
deps.api.waila=fabric-15.0.2
deps.api.badpackets=fabric-0.8.2
deps.api.iris=1.8.11+1.21.5-fabric
deps.api.sodium=mc1.21.5-0.6.13-fabric
deps.api.cloth-config=18.0.145+fabric
deps.api.nrc-emotes=1.0.29+fabric.1.21.5
deps.api.nrc-core=1.0.16+fabric.1.21.5